name: production
on:
 push:
  branches: [ main ]
jobs:
  deploy:
    name: deloy-on-wpengine
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
     - name: github-latest-clone
       uses: actions/checkout@v3
       with:
        fetch-depth: 2
     - name: FTP Deploy to WPEngine
       uses: wlixcc/SFTP-Deploy-Action@v1.2.4
       with:
         server: githubaction.sftp.wpengine.com
         username: githubaction-sftp-github  
         password: ${{ secrets.PROD_FTP_PASSWORD }}
         local_path: './wp-content/'
         remote_path: 'wp-content'
         port: 2222
         sftp_only: true